### ISSUE TITLE
Prototype DocBook Generation Based on OWL Data

### ISSUE THREAD

**Issue by melaasar** [opencaesar/docbook-tools#1]
## User Story
As a document author, I want to prototype using DocBook as a format to author my document using OWL data, so I can demonstrate its feasibility.

## Detailed Description
As a proof of concept, we want to test the data flow prior to coding automation. Using the GUI's provided, we will insert DocBook documents with OWL data.

## Acceptance Criteria
- [x] The ability to generate a document from an OWL dataset in PDF or HTML format that demonstrate the following features:
   - [x] page numbers
   - [x] table of contents
   - [x] paragraphs with static text
   - [x] paragraphs with dynamic text
   - [x] tables
   - [x] images
- [x] Document the next steps (design proposal) in a docs/Proposal.md document

## Sub-task List
- [x] Run Fuseki Server as a web application (Nic)
- [x] Load example OWL dataset to Fuseki (Nic/Steve)
- [x] Use Fuseki UI to execute a SPARQL query (Steve)
- [x] Save the result into a Table file
- [x] Author a DockBook that references the Table file (using Oxygen)
- [x] Render the DockBook to HTML (using Oxygen)
- [x] Render the DockBook to PDF (using Oxygen)
- [x] Define XSLT transformations as functions 
- [x] Invoke the XSLT transformations in DocBook

**Comment by truongdavid98** [comment]
Finished prototyping. The produced DocBook is supplied below.
[prototype_docbook.pdf](https://github.com/opencaesar/docbook-tools/files/4838133/prototype_docbook.pdf)
