### ISSUE TITLE
Develop DocBook adapter

### ISSUE THREAD

**Issue by truongdavid98** [opencaesar/docbook-tools#2]
## User Story
As a developer, I would like implement a tool to execute transformations on a DocBook so that we can automate tag replacement. 
## Detailed Description
Given a DocBook and an output location, we want to execute the XSLT to perform proper tag replacement. 

## Acceptance Criteria
- [x] Given a DocBook, and a directory to store the output, then output a DocBook with the tags properly replaced with the information from SPARQL frames. The frames will need to be stored in a frames directory.

## Sub-task List
- [x] Execute XSLT 
- [x] Save output DocBook
- [x] Ensure proper tag replacement is done 
- [x] Ensure the targeted SPARQL frames are targeted
